services:
  test_app:
    build:
      dockerfile: docker-build/app-tests/Dockerfile
      context: .
    image: fastapi-sdp-tools:tests
    container_name: test_app
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://test1:1111@192.168.200.3:5432/test
      APP_CONFIG__DB__ECHO: 1
      APP_CONFIG__default_superuser_creds__NAME: root
      APP_CONFIG__default_superuser_creds__PASSWORD: sdp2025
    command: ["fastapi", "dev", "--host", "0.0.0.0", "main.py", "--port", "7000"]
#    volumes:
#      - ./app:/app/app
    ports:
      - "8002:7000"
    networks:
      app_net2:
        ipv4_address: 192.168.200.2
    depends_on:
      test_pg:
       condition: service_healthy

  test_pg:
    image: postgres:18
    container_name: test_psgr
    environment:
      POSTGRES_USER: test1
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql
    ports:
      - "5433:5432"
    networks:
      app_net2:
        ipv4_address: 192.168.200.3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  app_net2:
    ipam:
      driver: default
      config:
        - subnet: "192.168.200.0/24"
          gateway: 192.168.200.1